server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movie-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
                
        - id: serie-service
          uri: lb://serie-service
          predicates:
            - Path=/serie-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: seriesService
                fallbackUri: forward:/fallback/series

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - LogFilter

  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

