server:
  port: 8061
  
spring:
  application:
    name: serie-service
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/SeriesFinalDB
      repositories:
        enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    
queue:
  serie:
    name: SerieQueue    

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
